### ISSUE TITLE
NoMethodError: undefined method `sub' for nil:NilClass

### ISSUE THREAD

**Issue by kschiess** [arunagw/omniauth-twitter#102]
Using omniauth-twitter (1.2.1) with sinatra (on Heroku), we get the following stacktrace once in a while: 

```
/gems/omniauth-twitter-1.2.1/lib/omniauth/strategies/twitter.rb:74 in image_url
/gems/omniauth-twitter-1.2.1/lib/omniauth/strategies/twitter.rb:21 in block in <class:Twitter>
/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:105 in instance_eval
/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:105 in block in compile_stack
/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:104 in each
/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:104 in inject
/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:104 in compile_stack
(eval):7 in info_stack
/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:321 in info
/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:334 in auth_hash
/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:361 in callback_phase
/gems/omniauth-oauth-1.1.0/lib/omniauth/strategies/oauth.rb:57 in callback_phase
/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:227 in callback_call
/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:184 in call!
/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164 in call
/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59 in call
/app/lib/platform/rack/caching.rb:26 in call
/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225 in context
/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220 in call
/gems/rack-timeout-0.2.4/lib/rack/timeout.rb:108 in call
/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24 in call
/gems/rack-ssl-enforcer-0.2.9/lib/rack/ssl-enforcer.rb:52 in call
```

Seems that we have users that haven't set their twitter image (`original_url`) - and that the info compilation fails because of that. 

Let me know if you need more! Would be glad to help eliminating this.

**Comment by raysrashmi** [comment]
As I know if user doesn't have image twitter respond with default image url.
Could you paste here your request options you are sending?

**Comment by raysrashmi** [comment]
@kschiess Do you still have this issue?

**Comment by kschiess** [comment]
No. We make many thousand calls to the twitter api every day, touching the data of a big number of twitter users. This error was only in our diagnostics once.

**Comment by fuji-nakahara** [comment]
I had the same error, but I couldn't reproduce it.
And I found https://github.com/arunagw/omniauth-twitter/issues/91 also reported the same thing.

Here are my environment and stack trace:

- #\87-Ubuntu SMP Wed Dec 2 22:52:11 UTC 2020
- ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
- related gems:
  - omniauth-twitter 1.4.0
  - omniauth-oauth 1.1.0
  - omniauth 1.9.1
  - oauth 0.5.4
  - rack 2.2.3

<details>
<summary>stack trace</summary>

```
NoMethodError: undefined method `sub' for nil:NilClass
  from omniauth-twitter (1.4.0) lib/omniauth/strategies/twitter.rb:92:in `image_url'
  from omniauth-twitter (1.4.0) lib/omniauth/strategies/twitter.rb:21:in `block in <class:Twitter>'
  from omniauth (1.9.1) lib/omniauth/strategy.rb:109:in `instance_eval'
  from omniauth (1.9.1) lib/omniauth/strategy.rb:109:in `block in compile_stack'
  from omniauth (1.9.1) lib/omniauth/strategy.rb:108:in `each'
  from omniauth (1.9.1) lib/omniauth/strategy.rb:108:in `inject'
  from omniauth (1.9.1) lib/omniauth/strategy.rb:108:in `compile_stack'
  from omniauth (1.9.1) lib/omniauth/strategy.rb:102:in `info_stack'
  from omniauth (1.9.1) lib/omniauth/strategy.rb:336:in `info'
  from omniauth (1.9.1) lib/omniauth/strategy.rb:349:in `auth_hash'
  from omniauth (1.9.1) lib/omniauth/strategy.rb:372:in `callback_phase'
  from omniauth-oauth (1.1.0) lib/omniauth/strategies/oauth.rb:57:in `callback_phase'
  from omniauth (1.9.1) lib/omniauth/strategy.rb:238:in `callback_call'
  from omniauth (1.9.1) lib/omniauth/strategy.rb:189:in `call!'
  from omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
  from omniauth (1.9.1) lib/omniauth/builder.rb:45:in `call'
  from sentry-rails (4.1.5) lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call'
  from rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
  from rack (2.2.3) lib/rack/etag.rb:27:in `call'
  from rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
  from rack (2.2.3) lib/rack/head.rb:12:in `call'
  from actionpack (6.1.1) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
  from actionpack (6.1.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
  from rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
  from rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
  from actionpack (6.1.1) lib/action_dispatch/middleware/cookies.rb:689:in `call'
  from actionpack (6.1.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
  from activesupport (6.1.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
  from actionpack (6.1.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
  from actionpack (6.1.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
  from actionpack (6.1.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
  from actionpack (6.1.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
  from railties (6.1.1) lib/rails/rack/logger.rb:37:in `call_app'
  from railties (6.1.1) lib/rails/rack/logger.rb:26:in `block in call'
  from activesupport (6.1.1) lib/active_support/tagged_logging.rb:99:in `block in tagged'
  from activesupport (6.1.1) lib/active_support/tagged_logging.rb:37:in `tagged'
  from activesupport (6.1.1) lib/active_support/tagged_logging.rb:99:in `tagged'
  from railties (6.1.1) lib/rails/rack/logger.rb:26:in `call'
  from actionpack (6.1.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  from actionpack (6.1.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'
  from rack (2.2.3) lib/rack/method_override.rb:24:in `call'
  from rack (2.2.3) lib/rack/runtime.rb:22:in `call'
  from activesupport (6.1.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  from actionpack (6.1.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
  from actionpack (6.1.1) lib/action_dispatch/middleware/static.rb:24:in `call'
  from rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
  from actionpack (6.1.1) lib/action_dispatch/middleware/ssl.rb:77:in `call'
  from actionpack (6.1.1) lib/action_dispatch/middleware/host_authorization.rb:92:in `call'
  from sentry-ruby (4.1.4) lib/sentry/rack/capture_exceptions.rb:29:in `block in call'
  from sentry-ruby (4.1.4) lib/sentry/hub.rb:52:in `with_scope'
  from sentry-ruby (4.1.4) lib/sentry-ruby.rb:147:in `with_scope'
  from sentry-ruby (4.1.4) lib/sentry/rack/capture_exceptions.rb:14:in `call'
  from railties (6.1.1) lib/rails/engine.rb:539:in `call'
  from puma (5.1.1) lib/puma/configuration.rb:246:in `call'
  from puma (5.1.1) lib/puma/request.rb:76:in `block in handle_request'
  from puma (5.1.1) lib/puma/thread_pool.rb:337:in `with_force_shutdown'
  from puma (5.1.1) lib/puma/request.rb:75:in `handle_request'
  from puma (5.1.1) lib/puma/server.rb:431:in `process_client'
  from puma (5.1.1) lib/puma/thread_pool.rb:145:in `block in spawn_thread'
```
</details>
