### ISSUE TITLE
Gzip response from twitter API

### ISSUE THREAD

**Issue by skyeagle** [arunagw/omniauth-twitter#70]
It is for ruby 2.0.

I had the exception at the beggining of authentication:

```
NoMethodError (undefined method `encoding' for nil:NilClass):
  /home/storage_production/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/cgi/util.rb:7:in `escape'
  oauth (0.4.7) lib/oauth/tokens/request_token.rb:29:in `block in build_authorize_url'
  oauth (0.4.7) lib/oauth/tokens/request_token.rb:29:in `each'
  oauth (0.4.7) lib/oauth/tokens/request_token.rb:29:in `map'
  oauth (0.4.7) lib/oauth/tokens/request_token.rb:29:in `build_authorize_url'
  oauth (0.4.7) lib/oauth/tokens/request_token.rb:9:in `authorize_url'
  omniauth-oauth (1.0.1) lib/omniauth/strategies/oauth.rb:37:in `request_phase'
  omniauth-twitter (1.0.1) lib/omniauth/strategies/twitter.rb:60:in `request_phase'
```

The investigation revealed that issue with gziped response from twitter api and ruby 2.0 doesn't handle it by default.
[This](http://stackoverflow.com/a/20470115) stackoverflow answer solves the issue.

**Comment by raysrashmi** [comment]
Closing. Reopen it if you still have this issue
